# Generated by Django 5.1.4 on 2025-01-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
